name: Update

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
  schedule:
    - cron: 0 */12 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Update:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Set git
      run : |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Update
      run: |

        rm -rf ./luci-app-pushbot
        rm -rf ./luci-app-serverchan
        rm -rf ./luci-app-easymesh
        rm -rf ./luci-app-ikoolproxy
        rm -rf ./luci-app-kodexplorer
        rm -rf ./theme-18.06/luci-theme-edge
        rm -rf ./theme-18.06/luci-theme-infinityfreedom
        rm -rf ./theme-18.06/luci-theme-neobird
        rm -rf ./lisaac/*  
        rm -rf ./linkease/app-store-ui
        rm -rf ./linkease/ddnsto
        rm -rf ./linkease/linkease
        rm -rf ./linkease/quickstart
        rm -rf ./linkease/luci-app-ddnsto
        rm -rf ./linkease/luci-app-linkease
        rm -rf ./linkease/luci-app-quickstart
        rm -rf ./linkease/luci-app-store
        rm -rf ./linkease/luci-app-ota
        rm -rf ./jerrykuku/*
        rm -rf ./op-oaf
        rm -rf ./op-fileBrowser/*
        rm -rf ./op-aliyun/*
        rm -rf ./op-socat/socat
        rm -rf ./op-mosdns/*
        rm -rf ./op-alist
        rm -rf ./patch/wall
        rm -rf ./patch/wall-luci
        
        ##自修改
        rm -rf ./op-adguardhome
        rm -rf ./path/autocore
        rm -rf ./theme
        rm -rf ./luci-app-vssr
        rm -rf ./lua-maxminddb
        rm -rf ./luci-app-jd-dailybonus
        
        
 
        git clone https://github.com/zzsj0928/luci-app-pushbot ./luci-app-pushbot
        git clone https://github.com/tty228/luci-app-serverchan ./luci-app-serverchan
        git clone https://github.com/ntlf9t/luci-app-easymesh ./luci-app-easymesh
        git clone https://github.com/yaof2/luci-app-ikoolproxy ./luci-app-ikoolproxy
        svn export https://github.com/Lienol/openwrt-package/trunk/luci-app-kodexplorer ./luci-app-kodexplorer
        
        ##docker&dockerman相关
        svn export https://github.com/lisaac/luci-lib-docker/trunk/collections/luci-lib-docker ./lisaac/luci-lib-docker
        svn export https://github.com/lisaac/luci-app-diskman/trunk/applications/luci-app-diskman ./lisaac/luci-app-diskman
        svn export https://github.com/lisaac/luci-app-dockerman/trunk/applications/luci-app-dockerman ./lisaac/luci-app-dockerman
        
        ##koolcenter相关插件
        svn export https://github.com/linkease/nas-packages-luci/trunk/luci/luci-app-ddnsto ./linkease/luci-app-ddnsto
        svn export https://github.com/linkease/nas-packages-luci/trunk/luci/luci-app-linkease ./linkease/luci-app-linkease
        svn export https://github.com/linkease/nas-packages-luci/trunk/luci/luci-app-quickstart ./linkease/luci-app-quickstart
        svn export https://github.com/linkease/nas-packages/trunk/network/services/ddnsto ./linkease/ddnsto
        svn export https://github.com/linkease/nas-packages/trunk/network/services/linkease ./linkease/linkease
        svn export https://github.com/linkease/nas-packages/trunk/network/services/quickstart ./linkease/quickstart
        svn export https://github.com/linkease/istore/trunk/luci/luci-app-store ./linkease/luci-app-store
        svn export https://github.com/linkease/istore-ui/trunk/app-store-ui ./linkease/app-store-ui
        svn export https://github.com/jjm2473/openwrt-apps/trunk/luci-app-ota ./linkease/luci-app-ota 
              
        ##jerrykuku开发插件
        git clone https://github.com/jerrykuku/luci-app-vssr ./luci-app-vssr
        git clone https://github.com/jerrykuku/lua-maxminddb ./lua-maxminddb
        git clone https://github.com/jerrykuku/luci-app-jd-dailybonus ./luci-app-jd-dailybonus
        

        git clone https://github.com/destan19/OpenAppFilter ./op-oaf
        
        ##主题
        svn export https://github.com/sirpdboy/sirpdboy-package/trunk/luci-theme-opentopd ./theme/luci-theme-opentopd
        svn export https://github.com/xiaoqingfengATGH/luci-theme-infinityfreedom/trunk/luci-theme-infinityfreedom ./theme/luci-theme-infinityfreedom-18.06
        #git clone https://github.com/kiddin9/luci-theme-edge -b 18.06 ./theme/luci-theme-edge-18.06 
        #git clone https://github.com/xiangfeidexiaohuo/luci-theme-neobird ./theme/luci-theme-neobird-18.06                         
        git clone https://github.com/jerrykuku/luci-theme-argon ./theme/luci-theme-argon
        git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon ./theme/luci-theme-argon-18.06
        git clone https://github.com/jerrykuku/luci-app-argon-config ./theme/luci-app-argon-config
        svn export https://github.com/281677160/openwrt-package/trunk/luci-theme-opentomcat ./theme/luci-theme-opentomcat
        
        svn export https://github.com/kiddin9/openwrt-packages/trunk/filebrowser ./op-fileBrowser/filebrowser
        svn export https://github.com/kiddin9/openwrt-packages/trunk/luci-app-filebrowser ./op-fileBrowser/luci-app-filebrowser
        
        svn export https://github.com/messense/aliyundrive-webdav/trunk/openwrt/aliyundrive-webdav ./op-aliyun/aliyundrive-webdav
        svn export https://github.com/messense/aliyundrive-webdav/trunk/openwrt/luci-app-aliyundrive-webdav ./op-aliyun/luci-app-aliyundrive-webdav
        svn export https://github.com/messense/aliyundrive-fuse/trunk/openwrt/aliyundrive-fuse ./op-aliyun/aliyundrive-fuse
        svn export https://github.com/messense/aliyundrive-fuse/trunk/openwrt/luci-app-aliyundrive-fuse ./op-aliyun/luci-app-aliyundrive-fuse

        ## wall相关
        git clone https://github.com/xiaorouji/openwrt-passwall ./patch/wall
        svn export https://github.com/coolsnowwolf/packages/trunk/net/redsocks2 ./patch/wall/redsocks2
        svn export https://github.com/xiaorouji/openwrt-passwall/branches/luci/luci-app-passwall ./patch/wall-luci/luci-app-passwall
        svn export https://github.com/fw876/helloworld/trunk/luci-app-ssr-plus ./patch/wall-luci/luci-app-ssr-plus
        svn export https://github.com/kiddin9/openwrt-bypass/trunk/luci-app-bypass ./patch/wall-luci/luci-app-bypass
        svn checkout https://github.com/vernesong/OpenClash/branches/dev/luci-app-openclash ./patch/wall-luci/luci-app-openclash
        
        svn export https://github.com/coolsnowwolf/packages/trunk/net/socat ./op-socat/socat
        git clone https://github.com/sbwml/luci-app-mosdns ./op-mosdns/
        git clone https://github.com/jjm2473/openwrt-alist ./op-alist/
        
        
        ##自修改
        git clone https://github.com/kiddin9/openwrt-adguardhome ./op-adguardhome
        svn co https://github.com/HiJwm/MySettings/trunk/lean/myautocore ./patch/autocore   
    
    - name: 删除多余文件
      run: |
        rm -rf ./.svn
        rm -rf ./*/.git
        rm -rf ./*/.github
        rm -rf ./*/*/.github
        rm -rf ./*/.svn
        #rm -rf ./*/README.md
        rm -rf ./*/LICENSE    
    
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3

  
    - name: Apply
      run: |
        git add .
        git commit -m "Sync: $(date +%Y-%m-%d" "%H:%M)"
        git push -f 
  
    
        
        
        
